runtime: nodejs16
handlers:
#serve all static file with url ending with a file extention
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
#catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html